### ISSUE TITLE
Do you sell ZUM BT-328?

### ISSUE THREAD

**Issue by janabee** [garthvh/garthvh.github.io#10]
I'm trying to put together the motherboard for the Ciclop scanner but I can only find it here: https://www.bqstore.nl/en/robotica/119-zum-bt-328

**Comment by garthvh** [comment]
I have the Ciclop Zum Scan PCB's which you found, I would recommend getting an Adafruit Metro in the US, it has a micro usb connector and SMB parts so it is flat on the bottom and flashed fine with the horus firmware https://www.adafruit.com/products/2488

**Comment by janabee** [comment]
Awesome, thank you! It's also a great deal cheaper. Does this fit into the Ciclop like the other one does? Or am I going to have to fudge it?

**Comment by garthvh** [comment]
It fits perfect because it also has a micro usb
