### ISSUE TITLE
PiGrrl case

### ISSUE THREAD

**Issue by MutkaHeki** [garthvh/garthvh.github.io#11]
I was wondering if you could print the PiGrrl with normal plastic action buttons? Only the start and select as Ninjaflex.

Thank you

**Comment by garthvh** [comment]
Sure

**Comment by MutkaHeki** [comment]
Also how much more will it cost and how do I place a special order with you?

Thank you for the quick responce.

**Comment by garthvh** [comment]
Are you wanting a pigrrl or pigrrl2? The price depends a bit on material and resolution, you can get a quote here https://garthvh.com/3d-Printing/ feel free to select PLA for the whole order and leave button / color details in the comments.

**Comment by MutkaHeki** [comment]
PIGRRL 2

**Comment by MutkaHeki** [comment]
Wanted it to look more like the original game boy. Black controls grey rubber start/select and red buttons. Is this possible with your supplies?

**Comment by garthvh** [comment]
You can buy the pigrrl 2 here https://garthvh.com/store/ via paypal

Pigrrl 2 is $29.99 shipped with screws, leave a note in your order about the buttons and I will print them as requested.

Thanks,

Garth

**Comment by garthvh** [comment]
I have everything but grey ninjaflex, I do have light gray PLA.

**Comment by MutkaHeki** [comment]
Now shipping to Canada says is min $10.00 but on PayPal it is saying only $5.00

**Comment by MutkaHeki** [comment]
Now shipping to Canada says is min $10.00 but on PayPal it is saying only $5.00

**Comment by garthvh** [comment]
Paypal is right, I have recently updated the costs, I will fix the website.

**Comment by MutkaHeki** [comment]
Thank you, order sent :)
