### ISSUE TITLE
3D Printing of PiGRRL 2 components

### ISSUE THREAD

**Issue by dayneprouse** [garthvh/garthvh.github.io#14]
Hello,

About 2 years ago I purchased a PiGRRL package from you which allowed me to select different colours for the top (PLA), bottom (PLA), and buttons (ninjaflex). A friend and I are both looking to build the newer version of the PiGRRL and I see you've upgraded and expanded your site. If I provide the 3D files, would there be a way to set up a few colour options? I suppose I could process a number of separate orders, but I can only imagine its easier for you (and cheaper for me) to ship everything in a single batch.

**Comment by garthvh** [comment]
Send me a mail at garthvh@yahoo.com and I can get you a quote.
