### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by imfullofthat** [garthvh/garthvh.github.io#16]
If it's not much of a bother. Would you happen to have a skeleton of the wifi manager you used for the "esp8266 Dash Like IoT Button using IFTTT with Captive Portal WiFi Setup" project? I am trying to to make a sensor that sends data to an MIT app. Being your connection/interface works pretty flawlessly I just cant the push-button portion. I've found different methods but no one has an interface that allows you to connect and reset all from the same screen. 

Look forward to hearing from you bud thanks.

**Comment by garthvh** [comment]
Just what is in the repo, I think there is a nice package for this purpose now.
