### ISSUE TITLE
3DHub printing

### ISSUE THREAD

**Issue by fnordpig** [garthvh/garthvh.github.io#18]
@garthvh 
Hi!  I order from you from time to time for pick up at your house or cloud city.  However on trying to order something, it informs me that 3dhub has changed their business model and I can't place an order through to you.  Not sure if this is something you'll still be offering with the change in business model?

https://www.3dhubs.com/blog/3d-hubs-announces-suite-of-new-features-and-switch-to-fulfilled-by-3d-hubs-2/

**Comment by garthvh** [comment]
I still have two printers and would be happy to give you a quote, garthvh@yahoo.com, I didn't really fit in to their new business model.

**Comment by garthvh** [comment]
2018
