### ISSUE TITLE
Zum Scan board

### ISSUE THREAD

**Issue by david0618** [garthvh/garthvh.github.io#4]
HI,
I have been wanting to build my own scanner.  I came across your site and really want to  get my hands on a Zum Scan board.   Do you sell just the board with out the components?  Can I order one from where you had yours made?  I would really appreciate your help.
Sincerely,
David

**Comment by garthvh** [comment]
I have one left  that I can sell for $30 shipped, it is fully assembled with 1 stepper driver.

You can also order the boards and parts from oshpark amazon and mouser if you want to order it yourself and assemble it, all of it is pretty easy through hole soldering

http://garthvh.com/oshpark/ciclop/2015/06/05/Order-a-PCB-and-build-your-own-Zum-Scan-Shield-using-OSHPark/

Thanks,

Garth

**Comment by david0618** [comment]
Hi Gath,
I will take it!   I really appreciate this.  Tell me how you want the funds and I'll take care of it today. 
Sincerely 
David Allevato

**Comment by garthvh** [comment]
You can send the money via paypal to garthvh@yahoo.com

Thanks,

Garth

**Comment by david0618** [comment]
Garth
Just sent via PayPal.   It came from my wife's account.  Please address it to David Allevato 2034 N Summit St. Wheaton, IL 60187


Thanks
David Allevato

**Comment by garthvh** [comment]
I added the tracking number to the paypal transaction, my scanner is at my office so I am going to make sure the board is working tomorrow before I ship it out.  I only have one jumper left currently and it needs 3 under the motor driver.

**Comment by garthvh** [comment]
Hi David,

I sent out the zum scan board after testing that it works, I could only find one jumper so you will have to find two more hard drive jumpers to put under the motor driver.  I also included this item http://www.thingiverse.com/make:144669 printed with Taulman Alloy 910, since the pins on the models only fit the BQ arduino.

Thanks,

Garth

**Comment by david0618** [comment]
Garth,I can't thank you enough for selling me this board.  It works perfectly and am very very happy with it.  Thank you again!!
Sincerely,Dave

Date: Wed, 11 Nov 2015 16:21:21 -0800
