### ISSUE TITLE
Shipping Retro Pigrrl Kits to Canada

### ISSUE THREAD

**Issue by dayneprouse** [garthvh/garthvh.github.io#6]
Hi Garth, I stumbled across your page while trying to source the 3D printed components for the Pigrrl. I noticed your page shows the kit shipped for $20 USD, would you be willing to ship to Canada? I'm living in Ottawa, Ontario. I ask because I'm pretty confident the $3.00 shipping won't quite cover the expense.

**Comment by garthvh** [comment]
Yeah I can ship to canada, I updated the shipping to be $10 which is about what it costs to canada generally so you can just use the button on the page

**Comment by dayneprouse** [comment]
Awesome, thanks for the quick reply!

**Comment by dayneprouse** [comment]
The paypal link is saying 'This merchant allows shipping to U.S. addresses only. Please enter a U.S. shipping address'

**Comment by garthvh** [comment]
There was one more checkbox, try it now

**Comment by dayneprouse** [comment]
Perfect, it works now! Just want to wait for our dollar to be slightly better... Thanks for your quick help!
